<?php

/**
 * @file
 * Contains tbo_emulate_hn.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;


/**
 * Implements hook_theme().
 */
function tbo_emulate_hn_theme(){
  return [                
    'emulate_session_hn' => [
      'variables' => [
        'uuid' => NULL,
        'title_view' => NULL,
        'form_config' => NULL,
        'fields' => NULL,
        'filters' => NULL,
        'directive' => NULL,
        'title' => NULL,
        'class' => NULL,
        'margin' => NULL,
      ],
      'template' => 'block--emulate-session',
    ],
    'unmasquerade_hn' => [
      'variables' => [
      'role' => NULL,
      ],
      'template' => 'block--unmasquerade-session',
    ],
    'company_selector_hn' => [
      'variables' => [
        'data' => [],
      ],
      'template' => 'block--company-selector-hn',
    ],
  ];
}
