adf_rest_api.adf_rest_api_endpoint_entity.*:
  type: config_entity
  label: 'Adf rest api endpoint entity config'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Service name'
    endpoint:
      type: string
      label: Endpoint
    method:
      type: string
      label: Method
    timeout:
      type: integer
      label: timeout
    client_id:
      type: string
      label: 'Client ID'
    client_secret:
      type: string
      label: Client Secret
    env_prefix:
      type: string
      label: Environment Prefix
    country_iso:
      type: string
      label: Country iso
    prefix_country:
      type: string
      label: Prefix country
    cache_time:
      type: integer
      label: Time in cache
